function u = crane_inner_loop(x, nu)

    I_tot=250;   l_B=2.5;     m_B=300;     I_B=156.25;     l_J=2;     m_J=250;     I_J=85;     g=9.81;       m=90;
    
    qdot = x(1:6);
    q = x(7:12); % Function changed for consistency, one state vector with [qdot; q]
    
    qa_dot = qdot(1:4);
    qu_dot = qdot(5:6);

    th1 = q(1);
    th2 = q(2);
    th3 = q(3);
    d6  = q(4);
    th4 = q(5);
    th5 = q(6);
    
    
    dth1 = qdot(1);
    dth2 = qdot(2);
    dth3 = qdot(3);
    dd6  =  qdot(4);
    dth4 = qdot(5);
    dth5  =qdot(6);
    
    
    
    M = [ I_tot + d6^2*m + l_B^2*m*cos(th2)^2 + l_J^2*m*cos(th3)^2 + (l_B^2*m_B*cos(th2)^2)/4 + l_B^2*m_J*cos(th2)^2 + (l_J^2*m_J*cos(th3)^2)/4 - d6^2*m*cos(th4)^2*cos(th5)^2 + 2*l_B*l_J*m*cos(th2)*cos(th3) + l_B*l_J*m_J*cos(th2)*cos(th3) + 2*d6*l_B*m*cos(th2)*sin(th5) + 2*d6*l_J*m*cos(th3)*sin(th5),                          d6*l_B*m*cos(th5)*sin(th2)*sin(th4),                          d6*l_J*m*cos(th5)*sin(th3)*sin(th4),            m*cos(th5)*sin(th4)*(l_B*cos(th2) + l_J*cos(th3)), d6*m*cos(th4)*cos(th5)*(l_B*cos(th2) + l_J*cos(th3) + d6*sin(th5)), -d6*m*sin(th4)*(d6 + l_B*cos(th2)*sin(th5) + l_J*cos(th3)*sin(th5));
                                                                                                                                                                                                                                                                     d6*l_B*m*cos(th5)*sin(th2)*sin(th4),                    I_B + l_B^2*m + (l_B^2*m_B)/4 + l_B^2*m_J,                       (l_B*l_J*cos(th2 - th3)*(2*m + m_J))/2, - l_B*m*sin(th2)*sin(th5) - l_B*m*cos(th2)*cos(th4)*cos(th5),                                d6*l_B*m*cos(th2)*cos(th5)*sin(th4),          -d6*l_B*m*(cos(th5)*sin(th2) - cos(th2)*cos(th4)*sin(th5));
                                                                                                                                                                                                                                                                    d6*l_J*m*cos(th5)*sin(th3)*sin(th4),                       (l_B*l_J*cos(th2 - th3)*(2*m + m_J))/2,                                I_J + l_J^2*m + (l_J^2*m_J)/4, - l_J*m*sin(th3)*sin(th5) - l_J*m*cos(th3)*cos(th4)*cos(th5),                                d6*l_J*m*cos(th3)*cos(th5)*sin(th4),          -d6*l_J*m*(cos(th5)*sin(th3) - cos(th3)*cos(th4)*sin(th5));
                                                                                                                                                                                                                                                      m*cos(th5)*sin(th4)*(l_B*cos(th2) + l_J*cos(th3)), - l_B*m*sin(th2)*sin(th5) - l_B*m*cos(th2)*cos(th4)*cos(th5), - l_J*m*sin(th3)*sin(th5) - l_J*m*cos(th3)*cos(th4)*cos(th5),                                                            m,                                                                  0,                                                                   0;
                                                                                                                                                                                                                                     d6*m*cos(th4)*cos(th5)*(l_B*cos(th2) + l_J*cos(th3) + d6*sin(th5)),                          d6*l_B*m*cos(th2)*cos(th5)*sin(th4),                          d6*l_J*m*cos(th3)*cos(th5)*sin(th4),                                                            0,                                           -d6^2*m*(sin(th5)^2 - 1),                                                                   0;
                                                                                                                                                                                                                                    -d6*m*sin(th4)*(d6 + l_B*cos(th2)*sin(th5) + l_J*cos(th3)*sin(th5)),   -d6*l_B*m*(cos(th5)*sin(th2) - cos(th2)*cos(th4)*sin(th5)),   -d6*l_J*m*(cos(th5)*sin(th3) - cos(th3)*cos(th4)*sin(th5)),                                                            0,                                                                  0,                                                              d6^2*m];
                                                                                                                                                                                                                            
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    C = [ 2*d6*dd6*m - dth2*l_B^2*m*sin(2*th2) - dth3*l_J^2*m*sin(2*th3) - (dth2*l_B^2*m_B*sin(2*th2))/4 - dth2*l_B^2*m_J*sin(2*th2) - (dth3*l_J^2*m_J*sin(2*th3))/4 - 2*d6*dd6*m*cos(th4)^2*cos(th5)^2 + 2*dd6*l_B*m*cos(th2)*sin(th5) + 2*dd6*l_J*m*cos(th3)*sin(th5) + 2*d6*dth5*l_B*m*cos(th2)*cos(th5) + 2*d6*dth5*l_J*m*cos(th3)*cos(th5) - 2*dth2*l_B*l_J*m*cos(th3)*sin(th2) - 2*dth3*l_B*l_J*m*cos(th2)*sin(th3) - dth2*l_B*l_J*m_J*cos(th3)*sin(th2) - dth3*l_B*l_J*m_J*cos(th2)*sin(th3) - 2*d6*dth2*l_B*m*sin(th2)*sin(th5) - 2*d6*dth3*l_J*m*sin(th3)*sin(th5) + 2*d6^2*dth4*m*cos(th4)*cos(th5)^2*sin(th4) + 2*d6^2*dth5*m*cos(th4)^2*cos(th5)*sin(th5),                                                                                                                                                                                                                                                         dd6*l_B*m*cos(th5)*sin(th2)*sin(th4) + d6*dth2*l_B*m*cos(th2)*cos(th5)*sin(th4) + d6*dth4*l_B*m*cos(th4)*cos(th5)*sin(th2) - d6*dth5*l_B*m*sin(th2)*sin(th4)*sin(th5),                                                                                                                                                                                                                                                         dd6*l_J*m*cos(th5)*sin(th3)*sin(th4) + d6*dth3*l_J*m*cos(th3)*cos(th5)*sin(th4) + d6*dth4*l_J*m*cos(th4)*cos(th5)*sin(th3) - d6*dth5*l_J*m*sin(th3)*sin(th4)*sin(th5),       dth4*l_B*m*cos(th2)*cos(th4)*cos(th5) + dth4*l_J*m*cos(th3)*cos(th4)*cos(th5) - dth2*l_B*m*cos(th5)*sin(th2)*sin(th4) - dth5*l_B*m*cos(th2)*sin(th4)*sin(th5) - dth3*l_J*m*cos(th5)*sin(th3)*sin(th4) - dth5*l_J*m*cos(th3)*sin(th4)*sin(th5), 2*d6^2*dth5*m*cos(th4)*cos(th5)^2 - d6^2*dth5*m*cos(th4) + dd6*l_B*m*cos(th2)*cos(th4)*cos(th5) + dd6*l_J*m*cos(th3)*cos(th4)*cos(th5) + 2*d6*dd6*m*cos(th4)*cos(th5)*sin(th5) - d6^2*dth4*m*cos(th5)*sin(th4)*sin(th5) - d6*dth2*l_B*m*cos(th4)*cos(th5)*sin(th2) - d6*dth4*l_B*m*cos(th2)*cos(th5)*sin(th4) - d6*dth5*l_B*m*cos(th2)*cos(th4)*sin(th5) - d6*dth3*l_J*m*cos(th4)*cos(th5)*sin(th3) - d6*dth4*l_J*m*cos(th3)*cos(th5)*sin(th4) - d6*dth5*l_J*m*cos(th3)*cos(th4)*sin(th5), d6*dth2*l_B*m*sin(th2)*sin(th4)*sin(th5) - d6^2*dth4*m*cos(th4) - dd6*l_B*m*cos(th2)*sin(th4)*sin(th5) - dd6*l_J*m*cos(th3)*sin(th4)*sin(th5) - d6*dth4*l_B*m*cos(th2)*cos(th4)*sin(th5) - d6*dth5*l_B*m*cos(th2)*cos(th5)*sin(th4) - d6*dth4*l_J*m*cos(th3)*cos(th4)*sin(th5) - d6*dth5*l_J*m*cos(th3)*cos(th5)*sin(th4) - 2*d6*dd6*m*sin(th4) + d6*dth3*l_J*m*sin(th3)*sin(th4)*sin(th5);
                                                                                                                                                                                                                                                     (dth1*l_B^2*m*sin(2*th2))/2 + (dth1*l_B^2*m_B*sin(2*th2))/8 + (dth1*l_B^2*m_J*sin(2*th2))/2 + (3*dd6*l_B*m*cos(th5)*sin(th2)*sin(th4))/2 + dth1*l_B*l_J*m*cos(th3)*sin(th2) + (dth1*l_B*l_J*m_J*cos(th3)*sin(th2))/2 + d6*dth1*l_B*m*sin(th2)*sin(th5) + (d6*dth2*l_B*m*cos(th2)*cos(th5)*sin(th4))/2 + (3*d6*dth4*l_B*m*cos(th4)*cos(th5)*sin(th2))/2 - (3*d6*dth5*l_B*m*sin(th2)*sin(th4)*sin(th5))/2, (dd6*l_B*m*cos(th2)*sin(th5))/2 - (dd6*l_B*m*cos(th4)*cos(th5)*sin(th2))/2 + (d6*dth5*l_B*m*cos(th2)*cos(th5))/2 - (dth3*l_B*l_J*m*cos(th2)*sin(th3))/2 + (dth3*l_B*l_J*m*cos(th3)*sin(th2))/2 - (dth3*l_B*l_J*m_J*cos(th2)*sin(th3))/4 + (dth3*l_B*l_J*m_J*cos(th3)*sin(th2))/4 - (d6*dth1*l_B*m*cos(th2)*cos(th5)*sin(th4))/2 + (d6*dth4*l_B*m*cos(th5)*sin(th2)*sin(th4))/2 + (d6*dth5*l_B*m*cos(th4)*sin(th2)*sin(th5))/2,                                                                                                                                                                                                                                                                                                                                                                       -(l_B*l_J*sin(th2 - th3)*(dth2 - 2*dth3)*(2*m + m_J))/4,             (dth2*l_B*m*cos(th4)*cos(th5)*sin(th2))/2 - dth5*l_B*m*cos(th5)*sin(th2) - (dth2*l_B*m*cos(th2)*sin(th5))/2 + dth4*l_B*m*cos(th2)*cos(th5)*sin(th4) + dth5*l_B*m*cos(th2)*cos(th4)*sin(th5) + (dth1*l_B*m*cos(th5)*sin(th2)*sin(th4))/2,                                                                                                                                                                                                                                                                  dd6*l_B*m*cos(th2)*cos(th5)*sin(th4) + d6*dth4*l_B*m*cos(th2)*cos(th4)*cos(th5) + (d6*dth1*l_B*m*cos(th4)*cos(th5)*sin(th2))/2 - (d6*dth2*l_B*m*cos(th5)*sin(th2)*sin(th4))/2 - d6*dth5*l_B*m*cos(th2)*sin(th4)*sin(th5),                                                             dd6*l_B*m*cos(th2)*cos(th4)*sin(th5) - dd6*l_B*m*cos(th5)*sin(th2) - (d6*dth2*l_B*m*cos(th2)*cos(th5))/2 + d6*dth5*l_B*m*sin(th2)*sin(th5) + d6*dth5*l_B*m*cos(th2)*cos(th4)*cos(th5) - (d6*dth2*l_B*m*cos(th4)*sin(th2)*sin(th5))/2 - d6*dth4*l_B*m*cos(th2)*sin(th4)*sin(th5) - (d6*dth1*l_B*m*sin(th2)*sin(th4)*sin(th5))/2;
                                                                                                                                                                                                                                                                                     (dth1*l_J^2*m*sin(2*th3))/2 + (dth1*l_J^2*m_J*sin(2*th3))/8 + (3*dd6*l_J*m*cos(th5)*sin(th3)*sin(th4))/2 + dth1*l_B*l_J*m*cos(th2)*sin(th3) + (dth1*l_B*l_J*m_J*cos(th2)*sin(th3))/2 + d6*dth1*l_J*m*sin(th3)*sin(th5) + (d6*dth3*l_J*m*cos(th3)*cos(th5)*sin(th4))/2 + (3*d6*dth4*l_J*m*cos(th4)*cos(th5)*sin(th3))/2 - (3*d6*dth5*l_J*m*sin(th3)*sin(th4)*sin(th5))/2,                                                                                                                                                                                                                                                                                                                                                                       -(l_B*l_J*sin(th2 - th3)*(2*m + m_J)*(2*dth2 - dth3))/4, (dd6*l_J*m*cos(th3)*sin(th5))/2 - (dd6*l_J*m*cos(th4)*cos(th5)*sin(th3))/2 + (d6*dth5*l_J*m*cos(th3)*cos(th5))/2 + (dth2*l_B*l_J*m*cos(th2)*sin(th3))/2 - (dth2*l_B*l_J*m*cos(th3)*sin(th2))/2 + (dth2*l_B*l_J*m_J*cos(th2)*sin(th3))/4 - (dth2*l_B*l_J*m_J*cos(th3)*sin(th2))/4 - (d6*dth1*l_J*m*cos(th3)*cos(th5)*sin(th4))/2 + (d6*dth4*l_J*m*cos(th5)*sin(th3)*sin(th4))/2 + (d6*dth5*l_J*m*cos(th4)*sin(th3)*sin(th5))/2,             (dth3*l_J*m*cos(th4)*cos(th5)*sin(th3))/2 - dth5*l_J*m*cos(th5)*sin(th3) - (dth3*l_J*m*cos(th3)*sin(th5))/2 + dth4*l_J*m*cos(th3)*cos(th5)*sin(th4) + dth5*l_J*m*cos(th3)*cos(th4)*sin(th5) + (dth1*l_J*m*cos(th5)*sin(th3)*sin(th4))/2,                                                                                                                                                                                                                                                                  dd6*l_J*m*cos(th3)*cos(th5)*sin(th4) + d6*dth4*l_J*m*cos(th3)*cos(th4)*cos(th5) + (d6*dth1*l_J*m*cos(th4)*cos(th5)*sin(th3))/2 - (d6*dth3*l_J*m*cos(th5)*sin(th3)*sin(th4))/2 - d6*dth5*l_J*m*cos(th3)*sin(th4)*sin(th5),                                                             dd6*l_J*m*cos(th3)*cos(th4)*sin(th5) - dd6*l_J*m*cos(th5)*sin(th3) - (d6*dth3*l_J*m*cos(th3)*cos(th5))/2 + d6*dth5*l_J*m*sin(th3)*sin(th5) + d6*dth5*l_J*m*cos(th3)*cos(th4)*cos(th5) - (d6*dth3*l_J*m*cos(th4)*sin(th3)*sin(th5))/2 - d6*dth4*l_J*m*cos(th3)*sin(th4)*sin(th5) - (d6*dth1*l_J*m*sin(th3)*sin(th4)*sin(th5))/2;
                                                                                                                                                                                                           d6*dth5*m*sin(th4) - d6*dth1*m + d6*dth1*m*cos(th4)^2*cos(th5)^2 - dth1*l_B*m*cos(th2)*sin(th5) - dth1*l_J*m*cos(th3)*sin(th5) + (dth4*l_B*m*cos(th2)*cos(th4)*cos(th5))/2 + (dth4*l_J*m*cos(th3)*cos(th4)*cos(th5))/2 - d6*dth4*m*cos(th4)*cos(th5)*sin(th5) - (3*dth2*l_B*m*cos(th5)*sin(th2)*sin(th4))/2 - (dth5*l_B*m*cos(th2)*sin(th4)*sin(th5))/2 - (3*dth3*l_J*m*cos(th5)*sin(th3)*sin(th4))/2 - (dth5*l_J*m*cos(th3)*sin(th4)*sin(th5))/2,                                                                                                                                                                                   dth2*l_B*m*cos(th4)*cos(th5)*sin(th2) - (dth5*l_B*m*cos(th5)*sin(th2))/2 - dth2*l_B*m*cos(th2)*sin(th5) + (dth4*l_B*m*cos(th2)*cos(th5)*sin(th4))/2 + (dth5*l_B*m*cos(th2)*cos(th4)*sin(th5))/2 - (dth1*l_B*m*cos(th5)*sin(th2)*sin(th4))/2,                                                                                                                                                                                   dth3*l_J*m*cos(th4)*cos(th5)*sin(th3) - (dth5*l_J*m*cos(th5)*sin(th3))/2 - dth3*l_J*m*cos(th3)*sin(th5) + (dth4*l_J*m*cos(th3)*cos(th5)*sin(th4))/2 + (dth5*l_J*m*cos(th3)*cos(th4)*sin(th5))/2 - (dth1*l_J*m*cos(th5)*sin(th3)*sin(th4))/2,                                                                                                                                                                                                                                                   0,                                                                                                                                                                                                                                                                                                    -(m*cos(th5)*(2*d6*dth4*cos(th5) + dth1*l_B*cos(th2)*cos(th4) + dth1*l_J*cos(th3)*cos(th4) + 2*d6*dth1*cos(th4)*sin(th5) + dth2*l_B*cos(th2)*sin(th4) + dth3*l_J*cos(th3)*sin(th4)))/2,                                                                                                       d6*dth1*m*sin(th4) - d6*dth5*m + (dth2*l_B*m*cos(th5)*sin(th2))/2 + (dth3*l_J*m*cos(th5)*sin(th3))/2 - (dth2*l_B*m*cos(th2)*cos(th4)*sin(th5))/2 - (dth3*l_J*m*cos(th3)*cos(th4)*sin(th5))/2 + (dth1*l_B*m*cos(th2)*sin(th4)*sin(th5))/2 + (dth1*l_J*m*cos(th3)*sin(th4)*sin(th5))/2;
                                                                            2*d6^2*dth5*m*cos(th4)*cos(th5)^2 - (d6^2*dth5*m*cos(th4))/2 + (dd6*l_B*m*cos(th2)*cos(th4)*cos(th5))/2 + (dd6*l_J*m*cos(th3)*cos(th4)*cos(th5))/2 + 2*d6*dd6*m*cos(th4)*cos(th5)*sin(th5) - (d6^2*dth4*m*cos(th5)*sin(th4)*sin(th5))/2 - d6^2*dth1*m*cos(th4)*cos(th5)^2*sin(th4) - (3*d6*dth2*l_B*m*cos(th4)*cos(th5)*sin(th2))/2 - (d6*dth4*l_B*m*cos(th2)*cos(th5)*sin(th4))/2 - (d6*dth5*l_B*m*cos(th2)*cos(th4)*sin(th5))/2 - (3*d6*dth3*l_J*m*cos(th4)*cos(th5)*sin(th3))/2 - (d6*dth4*l_J*m*cos(th3)*cos(th5)*sin(th4))/2 - (d6*dth5*l_J*m*cos(th3)*cos(th4)*sin(th5))/2,                                                                                                                                                                                              (dd6*l_B*m*cos(th2)*cos(th5)*sin(th4))/2 + (d6*dth4*l_B*m*cos(th2)*cos(th4)*cos(th5))/2 - (d6*dth1*l_B*m*cos(th4)*cos(th5)*sin(th2))/2 - d6*dth2*l_B*m*cos(th5)*sin(th2)*sin(th4) - (d6*dth5*l_B*m*cos(th2)*sin(th4)*sin(th5))/2,                                                                                                                                                                                              (dd6*l_J*m*cos(th3)*cos(th5)*sin(th4))/2 + (d6*dth4*l_J*m*cos(th3)*cos(th4)*cos(th5))/2 - (d6*dth1*l_J*m*cos(th4)*cos(th5)*sin(th3))/2 - d6*dth3*l_J*m*cos(th5)*sin(th3)*sin(th4) - (d6*dth5*l_J*m*cos(th3)*sin(th4)*sin(th5))/2,                                                                                                                 -(m*cos(th5)*(dth1*l_B*cos(th2)*cos(th4) + dth1*l_J*cos(th3)*cos(th4) + dth2*l_B*cos(th2)*sin(th4) + dth3*l_J*cos(th3)*sin(th4)))/2,                                                                                                                                                                                                                                                                                   (d6*m*cos(th5)*(4*dd6*cos(th5) - 4*d6*dth5*sin(th5) - dth2*l_B*cos(th2)*cos(th4) - dth3*l_J*cos(th3)*cos(th4) + dth1*l_B*cos(th2)*sin(th4) + dth1*l_J*cos(th3)*sin(th4) + d6*dth1*sin(th4)*sin(th5)))/2,                                                                                                                                                                                                        (d6*m*(d6*dth1*cos(th4) + dth1*l_B*cos(th2)*cos(th4)*sin(th5) + dth1*l_J*cos(th3)*cos(th4)*sin(th5) + dth2*l_B*cos(th2)*sin(th4)*sin(th5) + dth3*l_J*cos(th3)*sin(th4)*sin(th5)))/2;
                                                                         (3*d6*dth2*l_B*m*sin(th2)*sin(th4)*sin(th5))/2 - (d6^2*dth4*m*cos(th4))/2 - d6^2*dth4*m*cos(th4)*cos(th5)^2 - (dd6*l_B*m*cos(th2)*sin(th4)*sin(th5))/2 - (dd6*l_J*m*cos(th3)*sin(th4)*sin(th5))/2 - d6*dth1*l_B*m*cos(th2)*cos(th5) - d6*dth1*l_J*m*cos(th3)*cos(th5) - d6^2*dth1*m*cos(th4)^2*cos(th5)*sin(th5) - (d6*dth4*l_B*m*cos(th2)*cos(th4)*sin(th5))/2 - (d6*dth5*l_B*m*cos(th2)*cos(th5)*sin(th4))/2 - (d6*dth4*l_J*m*cos(th3)*cos(th4)*sin(th5))/2 - (d6*dth5*l_J*m*cos(th3)*cos(th5)*sin(th4))/2 - 2*d6*dd6*m*sin(th4) + (3*d6*dth3*l_J*m*sin(th3)*sin(th4)*sin(th5))/2,                                                                                    (dd6*l_B*m*cos(th2)*cos(th4)*sin(th5))/2 - (dd6*l_B*m*cos(th5)*sin(th2))/2 - d6*dth2*l_B*m*cos(th2)*cos(th5) + (d6*dth5*l_B*m*sin(th2)*sin(th5))/2 + (d6*dth5*l_B*m*cos(th2)*cos(th4)*cos(th5))/2 - d6*dth2*l_B*m*cos(th4)*sin(th2)*sin(th5) - (d6*dth4*l_B*m*cos(th2)*sin(th4)*sin(th5))/2 + (d6*dth1*l_B*m*sin(th2)*sin(th4)*sin(th5))/2,                                                                                    (dd6*l_J*m*cos(th3)*cos(th4)*sin(th5))/2 - (dd6*l_J*m*cos(th5)*sin(th3))/2 - d6*dth3*l_J*m*cos(th3)*cos(th5) + (d6*dth5*l_J*m*sin(th3)*sin(th5))/2 + (d6*dth5*l_J*m*cos(th3)*cos(th4)*cos(th5))/2 - d6*dth3*l_J*m*cos(th4)*sin(th3)*sin(th5) - (d6*dth4*l_J*m*cos(th3)*sin(th4)*sin(th5))/2 + (d6*dth1*l_J*m*sin(th3)*sin(th4)*sin(th5))/2, (dth2*l_B*m*cos(th5)*sin(th2))/2 + (dth3*l_J*m*cos(th5)*sin(th3))/2 - (dth2*l_B*m*cos(th2)*cos(th4)*sin(th5))/2 - (dth3*l_J*m*cos(th3)*cos(th4)*sin(th5))/2 + (dth1*l_B*m*cos(th2)*sin(th4)*sin(th5))/2 + (dth1*l_J*m*cos(th3)*sin(th4)*sin(th5))/2,                                                                                                                                                                                                    (d6^2*dth1*m*cos(th4))/2 - d6^2*dth1*m*cos(th4)*cos(th5)^2 + d6^2*dth4*m*cos(th5)*sin(th5) + (d6*dth1*l_B*m*cos(th2)*cos(th4)*sin(th5))/2 + (d6*dth1*l_J*m*cos(th3)*cos(th4)*sin(th5))/2 + (d6*dth2*l_B*m*cos(th2)*sin(th4)*sin(th5))/2 + (d6*dth3*l_J*m*cos(th3)*sin(th4)*sin(th5))/2,                                                                                                                                                        -(d6*m*(dth2*l_B*sin(th2)*sin(th5) - 4*dd6 + dth3*l_J*sin(th3)*sin(th5) + dth2*l_B*cos(th2)*cos(th4)*cos(th5) + dth3*l_J*cos(th3)*cos(th4)*cos(th5) - dth1*l_B*cos(th2)*cos(th5)*sin(th4) - dth1*l_J*cos(th3)*cos(th5)*sin(th4)))/2];
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    G = [                                0;
    (g*l_B*cos(th2)*(2*m + m_B + 2*m_J))/2;
         (g*l_J*cos(th3)*(2*m + m_J))/2;
                 -g*m*cos(th4)*cos(th5);
               d6*g*m*cos(th5)*sin(th4);
               d6*g*m*cos(th4)*sin(th5)];


    %% Deriving our matrices of interest

    Maa = M(1:4, 1:4); 
    Mau = M(1:4, 5:6);
    Mua = M(5:6, 1:4);
    Muu = M(5:6, 5:6);

    Caa = C(1:4, 1:4); 
    Cau = C(1:4, 5:6);
    Cua = C(5:6, 1:4);
    Cuu = C(5:6, 5:6);

    Ga = G(1:4);
    Gu = G(5:6);

    % Effective matrices

    M_bar = Maa - Mau*(Muu\Mua);
    Ca_bar = Caa - Mau*(Muu\Cua); Cu_bar = Cau - Mau*(Muu\Cuu); 
    G_bar = Ga - Mau*(Muu\Gu);

    %% Control law

    u = M_bar*nu + Ca_bar * qa_dot + Cu_bar * qu_dot + G_bar;



end